# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-01 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumblr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.CharField(default='pollete', max_length=500),
            preserve_default=False,
        ),
    ]
