# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-11 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumblr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set([]),
        ),
    ]
