# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-02 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tumblr', '0004_remove_audio_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
