# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-02 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tumblr', '0005_remove_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='name',
        ),
    ]
