# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-06 14:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tumblr', '0006_remove_video_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='videofile',
        ),
        migrations.AddField(
            model_name='quote',
            name='quote',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='quote',
            name='source',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='quote',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
