# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-16 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumblr', '0009_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='type',
            field=models.CharField(default='audio', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='chat',
            name='type',
            field=models.CharField(default='chat', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='link',
            name='type',
            field=models.CharField(default='link', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='quote',
            name='type',
            field=models.CharField(default='quote', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='text',
            name='type',
            field=models.CharField(default='text', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.CharField(default='video', editable=False, max_length=50),
        ),
    ]
