# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-16 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumblr', '0010_auto_20191116_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='user',
            field=models.CharField(max_length=500),
        ),
    ]
